#+title: Musings
#+author: Akshit Gaur
#+DESCRIPTION: ...
#+tags: musings
#+OPTIONS: toc:nil
#+DRAFT: false

Am I alone?

I think so

But who am I?

You are me

And who is speaking?

I am you

Well that doesn't make any sense

It doesn't have to

But it has to! What am I supposed to do if nothing makes sense?

You are not supposed to do anything

How am I even supposed to live then? If I am supposed to do nothing, what am I even here for?

You use the word "supposed" a lot, don't you?

...

One of the quiter ones huh

I am not quite!

Well, to answer your question, again you are not supposed to do anything but tha-

So I am not even supposed to live then?

Let me complete first, yes you are not supposed to do anything but that is different than "supposed to do nothing" you know

You are just confusing me, if I am not supposed to do anything, what is the point of doing /*ANYTHING*/?

Again, there is no point

So it doesn't matter if I die?

Death is the only certainty in life as you people say, why do you think yours will be any different this time

Even my parents won't remember me?

They will, but they too will move on

No they won't! They love me!

Yes they love you, but they WILL move on, the same way you moved on from that doll you loved as a kid

I just grew up...

So will they. The same way you continue to live on, they will too

If there is no point to anything then why even bother doing anything? Why should I eat? Why should I sleep? Why should I love? Why should I care?

The fact that there is no point, is THE entire point. Nothing needs to make sense because sense is not needed for you to function. You fear things out of your control, that is your bane

Of course I do! I am a human you know, of course I am going to fear things that can hurt me

But you fear things that have no impact on you. You dress up just so people on the street don't mock you, you fear being yourself just so others will like you. Just consider that girl you have a crush on, you analyse every move, both yours and hers, trying to find a signal that may or may not even be there!

So what! Should I just stop caring about others? If nothing matters, should I just go around punching random kids on the street!

You are still doing the same, just dumping the responsibilty of that answer on me

I can't even ask you a question?!

What do you think you have been doing till now :) The problem isn't you asking me a question, the problem is you asking an answer. You refuse to think about it, you refuse to take on that burden because you are afraid of what your answer could be

But if others hate me, what will I do? How will I live completely alone?

Why do you live?

What do you mean why do I live?

I mean why are you still alive, if you don't have any hope, why haven't you killed yourself?

Because people I care about, my parents, my friends, would be sad if I died

So you live for others?

Isn't that good enough?

You are making excuses, just like you always do. Pretending to be the forever victim, the one who couldn't have done any wrong, the one who fate has robbed at every turn.

...

You like having othes depend upon you, even if for the very smallest of the things, it satisfies that twisted little mind of yours, it makes you feel worth something.

That could be...

If you want real happiness, you have got to find it for yourself, not wait for somebody to give it to you! Isn't that what you have been doing?

I am worthless, nobody needs me.

You seek your value in the perce

AHHH SHUT UP!!!

ption of others. Do you fear being alone? You're afraid that you will lose your identity if others leave you

JUST LEAVE ME ALONE!! HOW CAN A FLOATING VOICE EVEN DARE TELL ME THAT!!

You're afraid that you will disappear from the mind of others. Each conversation they have that doesn't involve you, each inside joke that you are not part of, each knowing glance that you can't decipher scares you. Isn't that right?

No it is not, I want to be alone, I don't feel emotions since a long time, I have not cried in 5 years, I have always been alone and I like being alone. That is the reason I left my home and came to a new city for school. I want to be alone.

Was it really that or did you just want the attention to yourself? Tired of the fact that your brother was the one your mother has always liked more? What about when your entire family had that car crash and your mother kept looking for him, not even bothering to look at you? Or how your father was so focused on getting your mother in the hospital that he just left you with a stranger, with a broken and bleeding foot and a detached year? How old were you then, 13? 

I did not do it for attention. And anyways, nowadays the DO focus more on me!

Yes, after your brother disappointed them for 5 years straight. Huh, the same amount of years that took you to regain their trust after exactly two lies!! Do you think things will remain the same once he regains it too, as he is currently doing, or will they revert back to how things actually were? A 3 year old boy getting beaten up because he wanted his favourite song to play, a 8 year old getting beaten because his hand writing is not that good, a 15 year old getting beaten up because somebody stole the handle grips from his bicycle?

Even if they do, I don't care, things have always been like that and I have made my peace with it
